### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by baezortega**
I think this is ready to merge into master for release v1.1.

### CODE REVIEW

**Comment by kgori** [comment]
We should add a change log somewhere to document any function signatures that have changed, since we know this release breaks old code.

**Comment by baezortega** [comment]
Good point. Almost all the important functions have changed, and the plotting ones have lost arguments. Is there an easy way to compare function calls in both versions?

**Comment by kgori** [comment]
git diff?

**Comment by baezortega** [comment]
I've added a CHANGELOG file with the major changes that I found based on comparison between the two vignettes. Feel free to add/change anything, including the file name.

**Comment by baezortega** [comment]
Master is up to date now. We don't necessarily have to do a release yet, but I guess we should in order to change the package version in the DESCRIPTION file – so that users know this is a different version. I don't mind if it's v1.0.1 or v1.1.0 or else.

**Comment by kgori** [comment]
OK. I think v1.1.0, because there are breaking changes. Don't think there's much to do other than bumping the version number in the DESCRIPTION and adding a tag to the commit - this I think we can do directly through github in the browser.

**Comment by baezortega** [comment]
Done! https://github.com/kgori/sigfit/releases
I'll try a clean install of this version next week.

**Pull request merged**
